### ISSUE TITLE
Q.of_string doesn't follow the documentation

### ISSUE THREAD

**Issue by yminsky** [ocaml/Zarith#10]
In particular, it only parses fractions, e.g., 100221/19, rather than parsing decimals like 122.12.

The documentation, however, says this:

```ocaml
(** Converts a string to a rational.
    Plain decimals, and [/] separated decimal ratios (with optional sign) are
    understood.
    Additionally, the special [inf], [-inf], and [undef] are recognized
    (they can also be typeset respectively as [1/0], [-1/0], [0/0]).
 *)
```

The behavior is clear enough from looking at the implementation.

``` ocaml
let of_string s =
  try
    let i  = String.index s '/' in
    make
      (Z.of_substring s ~pos:0 ~len:i)
      (Z.of_substring s ~pos:(i+1) ~len:(String.length s-i-1))
  with Not_found ->
    if s = "inf" || s = "+inf" then inf
    else if s = "-inf" then minus_inf
    else if s = "undef" then undef
    else of_bigint (Z.of_string s)
```

I do think it would be great to support "plain decimals", but I suppose the minimum fix is to update the comment.

**Comment by yminsky** [comment]
In a related note, Neither Z nor Q support underscores. Also, once plain decimals are supported, scientific notation (e.g., 1.5e3) would be nice to have as well.

**Comment by antoinemine** [comment]
By 'decimal' in the documentation, I meant 'base-10 integers' (although other bases are actually supported). I've clarified the documentation.
The suggested improvements (support decimal point, underscore, scientific notations) are fine. I leave the issue open in case someone has time to add these.

**Comment by antoinemine** [comment]
I've merged PR #65 from Ghiles which implements most the requested features I believe (except underscore). Should we close the issue ?

**Comment by hhugo** [comment]
I think we should close this issue and open a new one about underscores

**Comment by hhugo** [comment]
I've opened #71. Please close this issue.
