### ISSUE TITLE
`to_bits` and `of_bits` for big endian ordering

### ISSUE THREAD

**Issue by pukkamustard** [ocaml/Zarith#100]
Hello,

I see that `to_bits` and `of_bits` return or read from little endian ordering. Would it be possible to also add functions for big-endian ordering?

I see that `to_bits` and `of_bits` are implemented in the C functions `ml_z_to_bits` and `ml_z_of_bits`. I assume adding corresponding big endian functions would entail implementing corresponding C functions? 

Could there be another way (without much C) of getting the big endian representation? It seems like GMP uses a big endian representation internally: https://gmplib.org/manual/Raw-Output-Internals.

I am interested in big endian representation for implementing CBOR ([RFC8949](https://www.rfc-editor.org/rfc/rfc8949.html)) in OCaml. In particular to support [Bignums](https://www.rfc-editor.org/rfc/rfc8949.html#name-bignums).

Thanks!

**Comment by xavierleroy** [comment]
In a hurry, you can always use the following OCaml function to change the byte ordering:
```
let string_reverse s =
    let l = String.length s in
    String.init l (fun i -> s.[l-1-i])

let z_to_bits_bigendian n = string_reverse (Z.to_bits n)
let z_of_bits_bigendian s = Z.of_bits (string_reverse s)
```

Nowadays, all popular processor architectures are little-endian (e.g. x86 and ARM), so protocols that insist on using big-endian representations are annoying.

Internally, GMP stores bignums least-significant-limb first.  It's just a few of GMP's conversion functions that use big-endian representation.

**Comment by pukkamustard** [comment]
> Internally, GMP stores bignums least-significant-limb first. It's just a few of GMP's conversion functions that use big-endian representation.

Ok. In that case maybe it does not makes sense to include a big-endian `to_bits`/`of_bits`. Byte-swapping in OCaml will do.

Thank you for your response. Closing this issue.
