### ISSUE TITLE
Build fails on Cygwin

### ISSUE THREAD

**Issue by kcrary** [ocaml/Zarith#101]
I get an error when trying to build on Cygwin:

$ ocamlc -v
The OCaml compiler, version 4.10.0
Standard library directory: /usr/lib/ocaml

$ ./configure
binary ocaml: found in /usr/bin
binary ocamlc: found in /usr/bin
binary ocamldep: found in /usr/bin
binary ocamlmklib: found in /usr/bin
binary ocamldoc: found in /usr/bin
binary gcc: found in /usr/bin
binary ocamlopt: found in /usr/bin
checking compilation with gcc -O3 -Wall -Wextra : working
include caml/mlvalues.h: found
library dynlink.cmxa: found
binary ocamlfind: not found
binary install: found in /usr/bin
OCaml's word size is 64
binary uname: found in /usr/bin
include gmp.h: found
library gmp: found
OCaml supports -bin-annot to produce documentation

detected configuration:

  native-code:          yes
  dynamic linking:      yes
  defines:              -DHAS_GMP 
  libraries:             -lgmp
  C options:            -O3 -Wall -Wextra 
  installation path:    /usr/lib/ocaml
  installation method   install

configuration successful!
now type "make" to build
then type "make install" or "sudo make install" to install

$ make
(echo "let"; grep "version" META | head -1) > zarith_version.ml
ocamldep -native  zarith_version.ml z.ml q.ml big_int_Z.ml z.mli q.mli big_int_Z.mli > depend
ocamlc -I +compiler-libs -bin-annot  -c zarith_version.ml
ocamlc -I +compiler-libs -bin-annot  -c z.mli
ocamlc -I +compiler-libs -bin-annot  -c z.ml
ocamlc -I +compiler-libs -bin-annot  -c q.mli
ocamlc -I +compiler-libs -bin-annot  -c q.ml
ocamlc -I +compiler-libs -bin-annot  -c big_int_Z.mli
ocamlc -I +compiler-libs -bin-annot  -c big_int_Z.ml
ocamlmklib -failsafe -o zarith zarith_version.cmo z.cmo q.cmo big_int_Z.cmo -lgmp
ocamlc -ccopt "-I/usr/lib/ocaml  -DHAS_GMP  -O3 -Wall -Wextra " -c caml_z.c
ocamlmklib -failsafe -o zarith caml_z.o -lgmp
ocamlc -I +compiler-libs -bin-annot  -c zarith_top.ml
File "zarith_top.ml", line 15, characters 16-45:
15 |   let phrase = !Toploop.parse_toplevel_phrase lexbuf in
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Toploop
make: *** [project.mak:135: zarith_top.cmo] Error 2

**Comment by xavierleroy** [comment]
Try to install the `ocaml-compiler-libs` Cygwin package.

**Comment by xavierleroy** [comment]
But you'd have a better experience by installing the OPAM package manager (`opam-installer` Cygwin package) and use that to install Zarith and other OCaml libraries and tools.

**Comment by kcrary** [comment]
That works, thank you!
