### ISSUE TITLE
Cannot enable executable stack on Ubuntu on Windows

### ISSUE THREAD

**Issue by adrien-n** [ocaml/Zarith#11]
Hi,

For « fun » I decided to try to build Prose (the collaborative text editor) on Windows/Ubuntu through its recent Linux subsystem. Well, for fun and to find out whether this subsystem could handle non-trivial workloads which include builds and packaging.

Build worked but ocsigenserver failed at runtime with the following error message:

> Error: Error on dynamically loaded library: /home/prose/.opam/4.04.2/lib/stublibs/dllzarith.so: /home/prose/.opam/4.04.2/lib/stublibs/dllzarith.so: cannot enable executable stack as shared object requires: Invalid argument\n

I don't know if the requirement on an executable stack comes from Zarith or from GMP so maybe I'm filling this issue report in the wrong project.

**Comment by antoinemine** [comment]
Zarith should not require an executable stack. However, I just discovered that compiling assembly files with gcc (unlike C files) produces objects with executable stacks by default, which is probably the source of your problem. I've pushed a fix that adds the required assembly directive to ask for a non-executable stack. I've checked, only on Linux x86_64, that it indeed produces an so file with non-executable stack.
Could you please check whether your problem does away with this patch?

**Comment by adrien-n** [comment]
Yes, this fixed the issue, thanks a lot!
