### ISSUE TITLE
trying to install zarith on cygwin (with opam, of course)

### ISSUE THREAD

**Issue by RBornat** [ocaml/Zarith#130]
## Installing conf-gmp fails, because of something about the include path.

cygwin comes with /usr/bin/cyggmp-10.dll. I didn't uninstall it, but I installed libgmp-devel, which gives me gmp.h and a different dll

      2021-08-21 18:12           0 usr/include/
      2021-08-21 18:12       84217 usr/include/gmp.h
      2021-08-21 18:12      129113 usr/include/gmpxx.h
      2021-08-21 18:12           0 usr/lib/
      2021-08-21 18:12      568946 usr/lib/libgmp.dll.a
      2021-08-21 18:12       72928 usr/lib/libgmpxx.dll.a
      2021-08-21 18:12           0 usr/lib/pkgconfig/
      2021-08-21 18:12         240 usr/lib/pkgconfig/gmp.pc
      2021-08-21 18:12         275 usr/lib/pkgconfig/gmpxx.pc

but the install still fails (and it seems a bad idea to try to uninstall /usr/bin/cyggmp-10.dll). There is no package gmp to install.

    richard@DESKTOP-9P95SLG ~
    $  ls -ld /usr/include/gmp.h
    -rw-r--r-- 1 richard Administrators 84217 Aug 21  2021 /usr/include/gmp.h

    richard@DESKTOP-9P95SLG ~
    $ opam install conf-gmp
    The following actions will be performed:
      ∗ install conf-gmp 4

    <><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

    <><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
    [ERROR] The compilation of conf-gmp failed at "C:\\OCaml64\\bin\\sh.exe -exc
        $(ocamlc -config | awk -F '[\t\r ]+' '/^bytecomp_c_compiler/
        {for(i=2;i<=NF;i++) printf \"%s \", $i}') -c $CFLAGS test.c".

    \#=== ERROR while compiling conf-gmp.4 =========================================#
    \# context     2.0.10 | win32/x86_64 | ocaml-variants.4.14.0+mingw64c | git+https ://github.com/fdopen/opam-repository-mingw.git#opam2
    \# path        ~/.opam/4.14.0+mingw64c/.opam-switch/build/conf-gmp.4
     ]+' '/^bytecomp_c_compiler/ {for(i=2;i<=NF;i++) printf "%s ", $i}') -c $CFLAGS test.c
    \# exit-code   1
    \# env-file    ~/.opam/log/conf-gmp-984-5a61c5.env
    \# output-file ~/.opam/log/conf-gmp-984-5a61c5.out
    \#\#\# output \#\#\#
    \# ++ ocamlc -config
     ]+' '/^bytecomp_c_compiler/ {for(i=2;i<=NF;i++) printf "%s ", $i}'
    \# + x86_64-w64-mingw32-gcc -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -c test.c
    \# test.c:1:10: fatal error: gmp.h: No such file or directory
    \#     1 | #include <gmp.h>
    \#       |          ^~~~~~~
    \# compilation terminated.

    <><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
    ┌─ The following actions failed
    │ λ build conf-gmp 4
    └─
    ╶─ No changes have been performed

    The packages you requested declare the following system dependencies. Please
    make sure they are installed before retrying:
        gmp

Clearly I'm doing something wrong. I got round this once before, but can't remember how.

**Comment by RBornat** [comment]
whoops, sorry, wrong place

**Comment by xavierleroy** [comment]
Hello Richard,

From the log it looks like you're using the Mingw64 version of OCaml (the one that produces native Win64 binaries) instead of the Cygwin version (the one that produces binaries that need the Cygwin DLL to run).  The telltale line is
```
x86_64-w64-mingw32-gcc -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -c test.c
```
For the Cygwin version, `x86_64-w64-mingw32-gcc` would be just `gcc`.

So, either
- you want the Mingw64 version of OCaml, in which case you should install the Mingw64 package for GMP (off the top of my head, I don't know where you can find it), or
- you want the Cygwin version of OCaml, in which case you can install it using the Cygwin package for OCaml (outdated?) or the Cygwin package for OPAM and then Cygwin-OPAM to install OCaml.

Hope this helps.

**Comment by RBornat** [comment]
Thanks for writing. Yes, it’s the mingw version I want, and it looks as if the opam repo can be persuaded to help. Annoying thing is that last month all this worked, but Mdx went for Microsoft MDM and my virtualbox windows just stopped working. It was mostly easy to recreate it, till I hit this snag. Richard Sent from my iPhoneOn 16 Feb 2023, at 17:25, Xavier Leroy ***@***.***> wrote:﻿
Hello Richard,
From the log it looks like you're using the Mingw64 version of OCaml (the one that produces native Win64 binaries) instead of the Cygwin version (the one that produces binaries that need the Cygwin DLL to run).  The telltale line is
x86_64-w64-mingw32-gcc -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -c test.c

For the Cygwin version, x86_64-w64-mingw32-gcc would be just gcc.
So, either

you want the Mingw64 version of OCaml, in which case you should install the Mingw64 package for GMP (off the top of my head, I don't know where you can find it), or
you want the Cygwin version of OCaml, in which case you can install it using the Cygwin package for OCaml (outdated?) or the Cygwin package for OPAM and then Cygwin-OPAM to install OCaml.

Hope this helps.
