### ISSUE TITLE
divisible is slow

### ISSUE THREAD

**Issue by craff** [ocaml/Zarith#140]
`divisible`is twice as slow as computing and testing the remainder. The C code seems not optimized and it seems better to implement it in ml using `mod` rather than providing a slower C implementation ? Probably `congruent` and a few other functions are affected ?

**Comment by antoinemine** [comment]
Yes, it is expected.  

A lot of less-used functions map directly to GMP, without an optimized path for small integers. Moreover, functions such as `divisible` have no `mpn` version, which means that we need a copy from Zarith's internal representation to a `mpz_t` number. Hence, they have some extra overhead. In theory, it should be faster for cases where GMP's `divisible`  is notably faster than a naive division (GMP's documentation says that this is the case if the divisor remains small).
