### ISSUE TITLE
Any plans to release new version?🤔

### ISSUE THREAD

**Issue by kloczek** [ocaml/Zarith#142]
https://github.com/ocaml/Zarith/compare/release-1.12...master shows +40 commits since last release which was +2y ago.
Any plans to release new version? 🤔

**Comment by xavierleroy** [comment]
Release 1.13 is out!

**Comment by kloczek** [comment]
Thank you 👍 😄

**Comment by xavierleroy** [comment]
Something may be wrong on macos ARM.  Until I can look into it, it's a "pre-release".

**Comment by stedolan** [comment]
> Something may be wrong on macos ARM. Until I can look into it, it's a "pre-release".

I spoke to @bgamari at ICFP, and he mentioned that GHC hit a bug in GMP on macos ARM - releases prior to 6.3.0 incorrectly make use of the reserved `x18` register in some assembly stubs. Could this be the issue you saw? Does it go away if you upgrade GMP?

**Comment by xavierleroy** [comment]
Thanks for the notice concerning the bug in some versions of GMP on ARM64/macOS.  I don't think Zarith ran into it (yet). What blocked release 1.13 for a few hours was a linking issue, which was "fixed" by reverting #124.
