### ISSUE TITLE
Requesting `Z.of_int128` and `Z.of_int256` and its unsigned versions 

### ISSUE THREAD

**Issue by basavesh** [ocaml/Zarith#146]
Requesting `Z.of_int128` and `Z.of_int256` and its unsigned versions `Z.of_int128_unsigned` and `Z.of_int256_unsigned`

I'm currently using int64 to represent 64 bit values in my project. Now I need to deal with 128 and 256 bits and need similar functionalities like `Z.of_int64`.  Could you please tell me how to achieve this?

If it is not very difficult, with the help of a mentor, I can try to get it done and contribute to the project. 

@antoinemine

**Comment by xavierleroy** [comment]
There are no built-in types for 128-bit integers and 256-bit integers in OCaml, so I don't understand your question.
