### ISSUE TITLE
Any hard feelings against Q.of_bigints?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/Zarith#151]
Chers collègues,

There is the pretty handsome Q.of_ints; hence I wonder why not Q.of_bigints ?

Thanks,
F.

**Comment by UnixJunkie** [comment]
Of course, I could write:
```ocaml
let x = Q.(of_bigint y / of_bigint z) in ...
```
but I don't feel it is very elegant.

**Comment by xavierleroy** [comment]
No hard feelings whatsoever, but this important basic operation is already implemented under the name `Q.make`:
```
val make: Z.t -> Z.t -> t
(** [make num den] constructs a new rational equal to [num]/[den].
    It takes care of putting the rational in canonical form.
 *)
```
Do we really need another name for this operation?

**Comment by UnixJunkie** [comment]
Ok, my bad.
