### ISSUE TITLE
Overflow in Big_int_Z.power_int_positive_int

### ISSUE THREAD

**Issue by maroneze** [ocaml/Zarith#19]
When given a ridiculously large number, `Big_int_Z.power_int_positive_int` aborts with the message:

    gmp: overflow in mpz type

In some cases, it would be better to be able to capture the error or to terminate in a less abrupt way.

For instance, the following program triggers this behavior:

    let () =
      let _ = Big_int_Z.power_int_positive_int 5 999999999999999 in
      ()

It seems the issue is in function `ml_z_pow`, in `caml_z.c`, when calling `mpz_pow_ui(mbase, mbase, e);`

The real issue seems to be upstream in gmp (e.g. https://stackoverflow.com/questions/3558684, https://stackoverflow.com/questions/13328409), but I wonder if something could be done in zarith to raise an OCaml exception instead.

**Comment by xavierleroy** [comment]
Apologies for not responding earlier.  The right thing to do would be for GMP to offer a proper API for reporting fatal errors.  As a stopgap measure, someone could reverse-engineer the cases where GMP can abort on fatal errors and try to anticipate them in the ZArith-GMP stubs, but this someone will not be me.

**Comment by antoinemine** [comment]
Well, it looks like the overflow test is performed from many places in gmp, and calls abort() immediately.
So, either we modify gmp to not abort (upstream), or we modify Zarith to avoid triggering the abort (Xavier's suggestion, a lot of work)... or we rely on the user to avoid calling Zarith functions that would make gmp overflow (should not be too hard on the user as Zarith is a thin layer on top of gmp, so, overflows are likely to be predictable).
I suggest we don't modify Zarith but only document the problem to inform the user.

**Comment by antoinemine** [comment]
OK. It turns out mpz_n_pow_ui has a rather simple computation to allocate a safe size to hold the result. We can copy this computation in ml_z_pow to check for any risk of trigerring "overflow in mpz type" before calling mpz_pow_ui, and raise an OCaml exception in that case. 
This is done in 14a496d97e2636237e3f6a4e0f8c97fccdff4602.
In theory, other functions could be affected, but I don't see that many functions that go from a number fitting comfortably in memory to a number with INT_MAX words (16 GB I guess) in one step.

**Comment by antoinemine** [comment]
Fun fact: big numbers represented in OCaml blocks can be much larger than GMP's mpz_t (signed 32-bit word size). A left-shift, e.g., that only uses OCaml blocks, can construct very large numbers, and only fail when we call a function based on mpz_t (such as pow, root, ...) that cannot handle such numbers. f5d05df checks for overflows before constructing mpz_t numbers and raises an OCaml exception.

**Comment by antoinemine** [comment]
Seems we now handle this issue as best as we can, with OCaml exceptions. Closing.
