### ISSUE TITLE
ZArith's built-in test suite reports errors on 64bit Windows (both native and on Cygwin) 

### ISSUE THREAD

**Issue by martin-neuhaeusser** [ocaml/Zarith#25]
While working on #23, it occurred to me that ZArith's own test suite consistently reports errors on Windows 64 bit builds. I attached the outputs of the zq. exe test binary here:
[zarith_test_failures.tar.gz](https://github.com/ocaml/Zarith/files/1597514/zarith_test_failures.tar.gz)

All tests have been conducted with OCaml 4.06.0 and the latest ZArith on github.

It seems that some floating-point precision is lost on both Windows ports. 
Even more disturbing, the results also differ between the Cygwin and the native built.
Platform-specific assembly code does not seem to influence the outcomes.

**Comment by xavierleroy** [comment]
Thank you for reporting this issue.  I think the computed results are correct, it's just the test itself that is poorly designed.  Namely, it prints large FP numbers with `%f` format, which forces many digits to be printed, well beyond the precision of the FP number.   For example:
``` to_float 2^300
- = 2037035976334486086268445688409378161051468393665936250636140449354381299763336706183397376.000000
+ = 2037035976334486086268445688409378161051468000000000000000000000000000000000000000000000000.000000
```
The two printed values look different, but are actually equal when converted back to a double-precision FP number.

OCaml delegates the printing of FP numbers to the C standard library, so different C libraries (e.g. Linux vs Cygwin vs Microsoft) can print the same FP number differently.

I'll look into making the test more robust.

**Comment by xavierleroy** [comment]
Commit 37aeb86 should fix this issue.
