### ISSUE TITLE
Polymorphic comparison over `Q.t` values

### ISSUE THREAD

**Issue by grantpassmore** [ocaml/Zarith#34]
Is there a fundamental impediment to supporting OCaml's polymorphic comparison operators over `Q.t` values? Could it be done similarly to how it's done for `Z.t` values (e.g., via something like `ml_z_custom_compare`)?

If there's no fundamental issue making this not possible, we could perhaps try to do this.

Many thanks.

**Comment by antoinemine** [comment]
Unfortunately, there is a fundamental issue. As far as I know, OCaml's polymorphic comparison can only be overloaded for custom blocks. Z.t is a custom block, but Q.t is a pure OCaml's data-structure. We'd need to develop a new library for Q.t based on custom blocks.

**Comment by grantpassmore** [comment]
Understood -- many thanks.
