### ISSUE TITLE
host online documentation on github

### ISSUE THREAD

**Issue by c-cube** [ocaml/Zarith#35]
I can't make a PR because gh-pages is an orphan branch, but if anyone with admin rights wants to pull from my fork:

- branch gh-pages here: https://github.com/c-cube/Zarith/tree/gh-pages (with generated doc)
- points to https://c-cube.github.io/Zarith/ with the online docs for people who desperately search it online (here it'd be https://ocaml.github.io/Zarith/)

**Comment by antoinemine** [comment]
Thanks.
I've put the generated documentation on https://antoinemine.github.io/Zarith/doc/latest/

**Comment by c-cube** [comment]
Should this point to ocaml.github.io/zarith now? And with a link from the github repo (on the right hand side under "about")?
