### ISSUE TITLE
`Q.compare` handles NaN surprisingly

### ISSUE THREAD

**Issue by chengsun** [ocaml/Zarith#36]
Hi all,

I noticed that `Q.compare` has the following semantics for comparing with NaN:

```ocaml
let nan = Q.(zero / zero);;

Q.compare nan Q.(neg inf);;
(* -1 *)

Q.compare nan nan;;
(* 0 *)
```

This was a little surprising to me, as these comparisons imply that NaN is "smaller" than all other bignums, including negative infinity. More specifically, I was expecting a behaviour similar to IEEE 754 floating point, where all inequalities involving NaN return false, and NaN <> any value.

Looking at the code, it seems to me like this behaviour was deliberately chosen:
https://github.com/ocaml/Zarith/blob/cda0bb6/q.ml#L146
Could someone explain the rationale behind having NaN compare in this way?

Thanks in advance!
Cheng

**Comment by yakobowski** [comment]
(I'm not a Zarith developer.)

The semantics given by IEEE 754 to NaN comparisons is problematic in a language such as OCaml, where the `compare` function is used to distinguish elements in containers such as sets. For those, you need a total order, which IEEE 754 does not offer with the default semantics.

Note that the behavior of `Q.Compare` is consistent with  the `compare` function of OCaml:

```
# compare nan infinity;;
- : int = -1
# compare infinity nan;;
- : int = 1
# compare nan nan;;
- : int = 0
```

(This is only true for `compare`. The other comparison operators follow IEEE 754
```
# nan < infinity;;
- : bool = false
# infinity < nan;;
- : bool = false
# nan = nan;;
- : bool = false
```

**Comment by chengsun** [comment]
> The semantics given by IEEE 754 to NaN comparisons is problematic in a language such as OCaml, where the compare function is used to distinguish elements in containers such as sets. For those, you need a total order, which IEEE 754 does not offer with the default semantics.

Understood, and agreed.

> The other comparison operators follow IEEE 754

I can't reproduce the results that you demonstrated here. Which infix comparison functions are you using? According to what I can see in the code (https://github.com/ocaml/Zarith/blob/cda0bb6/q.ml#L365), the infix operators for `Q` all boil down to a call to `compare`.

Assuming I'm understanding correctly, I would be in support of changing just the infix operators (and related functions like `min` and `max`) to behave like IEEE 754, whilst maintaining the current total-ordering behaviour for `compare` only. Thoughts?

**Comment by yakobowski** [comment]
Sorry, those examples were meant to be tested in OCaml's toplevel. Apparently the semantics was chosen to be different for Zarith.

As for which semantics should be implemented, I was never really fond of the semantics of `<`, `=` and co in OCaml. But perhaps Zarith ought to be consistent indeed.

**Comment by xavierleroy** [comment]
Thanks @chengsun and @yakobowski for an interesting discussion.

As @yakobowski wrote, it's best if three-valued comparison functions like `Q.compare` implement a total order: these comparisons are often used for sorting or for ordering binary search trees, and for these purposes IEEE754-like behavior (`Q.undef` different from all numbers including itself) is just useless.  Claiming that `Q.undef` is equal to itself and less than any other number is arbitrary, but enough to make the order total.

As @chengsun wrote, a case can be made that `Q.{equal,leq,geq,lt,gt,min,max}` should treat `undef` the IEEE754 way.  The implementation effort is modest.  What we should discuss is whether the IEEE754 behavior is really better.

**Comment by chengsun** [comment]
I have no opinion over whether IEEE-754's treatment of NaNs is objectively better.
However, I do think that IEEE-754 behaviour is more standard, and hence less surprising. This difference shows up very unexpectedly, when porting code operating on OCaml's `float`s (which do compare the IEEE-754 way) to use `Zarith.Q` instead.

**Comment by antoinemine** [comment]
PR #52 changes Q.leq, Q.geq,  Q.equal to return false for NaN arguments. 
Q.compare is not changed (so, no IEEE compliant).
This seems to be consistent with OCaml's behavior.
What do you think ? Is this worth it ? Can it break existing code ?
Also, min, max are unchanged (not sure what we should do with them).

**Comment by antoinemine** [comment]
OK, I've merge the PR as this is a more consistent behavior with IEEE and OCaml.
