### ISSUE TITLE
Problem with compilation - Unbound module Z, error during linking

### ISSUE THREAD

**Issue by daniel-fs** [ocaml/Zarith#37]
Hi there,

I've been trying to get compilation with Zarith to work, but I'm having some trouble.

I have installed Zarith with the "opam install zarith" command. I also have everything from the Requirements section installed. I'm on Linux Mint 18.

Opam version is 1.2.2 and Ocaml version is 4.02.3.

The commands "opam list" and "ocamlfind list" do have zarith listed as an installed package.

I've tried to compile the code in different ways to no avail. Let's say I have a single line "let x = Z.of_int 4" in a test.ml file.

If I do compilation with "ocamlopt -I +zarith test.ml" I get:
Error: Unbound module Z

With "ocamlfind ocamlopt -package zarith test.ml":
test.o: In function `camlTest__entry':
test.ml:(.text+0xc): undefined reference to `ml_z_of_int'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking

I also tried "ocamlopt zarith.cmxa test.ml", which gives me:
Error: Cannot find file zarith.cmxa

However, in the OCaml TopLevel, if I call:
#require "zarith";;
#load "zarith.cma";;

I can use the module just fine, inside the TopLevel.

How could I fix this problem with the compilation? Thank you in advance.

**Comment by antoinemine** [comment]
You can use the -linkpkg option when linking with ocamlfind. So 
`ocamlfind ocamlopt -package zarith test.ml -linkpkg` 
should work.

**Comment by daniel-fs** [comment]
> You can use the -linkpkg option when linking with ocamlfind. So
> `ocamlfind ocamlopt -package zarith test.ml -linkpkg`
> should work.

I wasn't aware of that option. I tried it and now it compiled. Thanks!
