### ISSUE TITLE
Unable to install zarith on OpenSuse

### ISSUE THREAD

**Issue by abhi18av** [ocaml/Zarith#40]
Hello everyone, 

I was trying to install `zarith` on my `opensuse` server however, I'm running into issues wrt `gmp` 

I've also reported this issue here https://github.com/ocaml/opam-repository/issues/12926

**Comment by antoinemine** [comment]
This is a bit old, and seemed to be related more to the package manager than to Zarith. Any news on this ? Any fix needed on our part ? If not, I suggest we close the issue.

**Comment by avsm** [comment]
I think this can be closed in favour of the opam-repository one. I suspect it was due to depext issues on opensuse that have since been fixed.

**Comment by antoinemine** [comment]
OK, closing...
