### ISSUE TITLE
win10 make failure - wait-process.c:298: undefined reference to `waitpid'

### ISSUE THREAD

**Issue by BlueL87** [ocaml/Zarith#48]
Hi guys, 

When I tried to build and install Zarith, after configure it, it showed me below error. 
I'm using windows 10, cygwin + OPAM (which provided by OCaml 64bit windows installation).

Could you give me some suggestions on it? Thank you very much!

The error:

Steve@DESKTOP-HI9GPS4 /cygdrive/d/zarith
$ make
make  all-recursive
make[1]: Entering directory '/cygdrive/d/zarith'
Making all in .
make[2]: Entering directory '/cygdrive/d/zarith'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/cygdrive/d/zarith'
Making all in examples
make[2]: Entering directory '/cygdrive/d/zarith/examples'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/cygdrive/d/zarith/examples'
Making all in lib
make[2]: Entering directory '/cygdrive/d/zarith/lib'
make  all-am
make[3]: Entering directory '/cygdrive/d/zarith/lib'
make[3]: Leaving directory '/cygdrive/d/zarith/lib'
make[2]: Leaving directory '/cygdrive/d/zarith/lib'
Making all in src
make[2]: Entering directory '/cygdrive/d/zarith/src'
x86_64-w64-mingw32-gcc.exe   -g -O2   -o m4.exe m4.o builtin.o debug.o eval.o format.o freeze.o input.o macro.o output.o path.o symtab.o ../lib/libm4.a
../lib/libm4.a(wait-process.o): In function `wait_subprocess':
/cygdrive/d/m4/lib/wait-process.c:298: undefined reference to `waitpid'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1491: m4.exe] Error 1
make[2]: Leaving directory '/cygdrive/d/zarith/src'
make[1]: *** [Makefile:1506: all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/d/zarith'
make: *** [Makefile:1461：all] Error 2

Cheers,
Steve

**Comment by BlueL87** [comment]
May I ask what is the best way to install Zarith in a Windows machine? 
I used to tried to use OPAM to install it but always failed with cannot find GMP library, although I already built and installed GMP. So I tried to build and install Zarith myself, rather than use the command to install the package (OPAM install zarith).

Thank you so much!

**Comment by xavierleroy** [comment]
From the short log you give, it looks like your `/cygdrive/d/zarith` directory contains not the ZArith sources, but perhaps the GNU M4 sources.  Please try again with a fresh download of the ZArith sources.

**Comment by BlueL87** [comment]
> 
> 
> From the short log you give, it looks like your `/cygdrive/d/zarith` directory contains not the ZArith sources, but perhaps the GNU M4 sources. Please try again with a fresh download of the ZArith sources.

Thank you so much! Let me try it and see ~~

**Comment by BlueL87** [comment]
> 
> 
> From the short log you give, it looks like your `/cygdrive/d/zarith` directory contains not the ZArith sources, but perhaps the GNU M4 sources. Please try again with a fresh download of the ZArith sources.

I re-cloned https://github.com/ocaml/Zarith.git and tried again, but unfortunately got
