### ISSUE TITLE
Zarith 1.8 is not available on opam

### ISSUE THREAD

**Issue by hhugo** [ocaml/Zarith#50]

**Comment by antoinemine** [comment]
I suggest we put the .opam file in the repository. See PR #53.
When we're happy with it, we can "opam publish -v 1.8" and future versions.

Note that, due to issue #49, 1.8 might not compile cleanly for everyone. Should we actually publish it, or wait for a 1.9 ?

**Comment by hhugo** [comment]
> Note that, due to issue #49, 1.8 might not compile cleanly for everyone. Should we actually publish it, or wait for a 1.9 ?

I'm fine either way

**Comment by hannesm** [comment]
tbh I prefer a 1.8.1 or 1.9.0 with the fix for #49 -- in my opinion there's not much sense to release a package that's known to not compile on certain environments (esp. if there's already a fix merged)
