### ISSUE TITLE
Document js_of_ocaml support ?

### ISSUE THREAD

**Issue by hhugo** [ocaml/Zarith#64]
https://github.com/janestreet/zarith_stubs_js just got released. How do you feel about adding a section in the readme about it ?

**Comment by antoinemine** [comment]
Sorry for not commenting earlier. I guess it would make more sense to ask the people at js_of_ocaml to add the link in their Supported features documentation (they already mention num).

**Comment by hhugo** [comment]
> Sorry for not commenting earlier. I guess it would make more sense to ask the people at js_of_ocaml to add the link in their Supported features documentation (they already mention num).

js_of_ocaml doesn't support zarith out of the box (unlike num). The support is provided by janestreet/zarith_stubs_js. It makes more sense to me to have a cross-reference between zarith and zarith_stubs_js. I've opened #144 with a proposal.

**Comment by hhugo** [comment]
#144 was merged.
