### ISSUE TITLE
Q.t is exposed, allowing construction of non-canonical values

### ISSUE THREAD

**Issue by Elnatan** [ocaml/Zarith#69]
q.mli describes the canonical representation of rational numbers, but the type is exposed, so one can construct non-canonical values. Perhaps the type should be made abstract or private to ensure proper behavior?

**Comment by antoinemine** [comment]
Calling `make` to construct a canonical value incurs a non-negligible cost (GCD computation). This can be avoided in some cases when you know that the rational is already in canonical form. As this this a fairly low-level library, I think it is best to leave the choice to the programmer on whether to call `make` or not to construct a rational.

If this is a big concern, we could make the type abstract and export a `make_unsafe` function that does not perform canonicalisation. But perhaps it is sufficient to state in the documentation that (almost) all the functions in the library assume that the arguments are in canonical form and output results in canonical form.

**Comment by antoinemine** [comment]
This no does not seem to be a large concern after all, I'm closing.
