### ISSUE TITLE
(approximate) conversion to float

### ISSUE THREAD

**Issue by smolkaj** [ocaml/Zarith#7]
`Q` is missing a `to_float : t -> float` function that converts the rational `q` to the floating point number `to_float q` that best approximates `q`.

**Comment by smolkaj** [comment]
It looks like I'm not the first to observe this: http://stackoverflow.com/questions/33623875/converting-an-arbitrary-precision-rational-number-ocaml-zarith-to-an-approxim.

Looks like the best way to do this would be to call GMPs `mpq_get_d` function.

**Comment by xavierleroy** [comment]
Implemented in commit [5463dbc].  My limited experiments with `mpq_get_d` suggest that it doesn't round exactly (1 ulp error).  The implementation I used is taken from the Num library of the OCaml standard distribution and relies on the round-to-odd technique outlined in the StackOverflow question.

**Comment by smolkaj** [comment]
Fantastic, thanks!
