### ISSUE TITLE
there is no ocamldoc in Big_int_Z

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/Zarith#76]

**Comment by UnixJunkie** [comment]
I could send a PR with the corresponding ocamldoc found in Big_int, if you are interested.

**Comment by xavierleroy** [comment]
Thanks for the offer.  But I'm not sure we want to document `Big_int_Z`: I'd rather steer users towards the more modern `Z` interface.

**Comment by UnixJunkie** [comment]
Ok, fair enough.
