### ISSUE TITLE
Is this library safe to `Hashtbl.hash_param`?

### ISSUE THREAD

**Issue by LdBeth** [ocaml/Zarith#81]
If two numbers are qual by `=` operator, will it be guaranteed that `hash_param` still return same results?

**Comment by antoinemine** [comment]
Yes, all the hashing functions should return equal results for equal arguments (for =).

**Comment by xavierleroy** [comment]
That's what I thought too, but there is an issue with `min_int` represented as a `Z.t`, see #83 .
