### ISSUE TITLE
Make a new release (1.11 ?) 

### ISSUE THREAD

**Issue by hhugo** [ocaml/Zarith#82]
- Including the recent fixes on the `Q.of_string` and `Z.of_string`

**Comment by hhugo** [comment]
@antoinemine , are there any issue / PR you want to see addressed / merged before a new release ?

**Comment by antoinemine** [comment]
I've been meaning to go through open issues and PR... sorry it got delayed.
After a quick check, there is no more issues or PR to handle at this point. The remaining ones are related to #79, minor enhancements, or related to Windows (without much recent activity). I will make the release later today.

**Comment by hhugo** [comment]
thanks
