### ISSUE TITLE
Suggestion: fast path for ml_z_extract when len < Z_BASE2_LENGTH_OP

### ISSUE THREAD

**Issue by recoules** [ocaml/Zarith#88]
`ml_z_extract` have a fast path if its argument is a `natint` but it could also use the fact that its result will be a `natint` if `len` argument is  lower than `Z_BASE2_LENGTH_OP` -- saving the cost of allocating a limb just before reducing it to a `natint`.

**Comment by antoinemine** [comment]
It could be possible. 
Note that it requires writing a whole new path that implements gluing together bits of limbs and properly handling negative numbers, so, not trivial... Maybe there's a possibility to share part of the existing code (using `mpn_rshift` and co., but in a statically allocated limb buffer). I'm not sure we gain much in terms of performance.
I keep this open as a possible enhancement for the future, when we have time. You can speed up the process by proposing a MR for it ;)

**Comment by antoinemine** [comment]
Closed by #90, merged.
