### ISSUE TITLE
Z.one Error : Unbound module Z

### ISSUE THREAD

**Issue by fredOnGitHub** [ocaml/Zarith#9]
Hello

i have installed zarith with 

opam depext zarith
opam install zarith

and with ocaml-top
i have to put this way

#load "/Users/uio/.opam/system/lib/zarith/zarith.cma";;

because #load "zarith.cma";; doesn't work (cannot find file zarith.cma)

with function example test from zarith source

let rec fib_z n =
if n < 2 then Z.one else Z.add (fib_z(n-1)) (fib_z(n-2))

i get 

...Z.one Error : Unbound module Z

Here my PATH
echo $PATH
/Users/uio/.opam/system/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

Thanks

**Comment by xavierleroy** [comment]
Zarith is installed with findlib/ocamfind, so, to use it under an interactive toplevel, it's best to go through findlib/ocamlib as well, as follows:
```
#use "topfind";;
#require "zarith";;
```
For more info on findlib and the toplevel:  http://projects.camlcity.org/projects/dl/findlib-1.7.3/doc/guide-html/x231.html

The problem and the explanations above are not specific to Zarith and apply to any other ocamlfind package.
