### ISSUE TITLE
Add Zarith formula to Homebrew

### ISSUE THREAD

**Issue by tchajed** [ocaml/Zarith#95]
Coq 8.13 now has a hard dependency on Zarith and can no longer use Num, so Homebrew needs a formula for ocaml-zarith in analogy to ocaml-num.

I did what I could to write that formula at https://github.com/Homebrew/homebrew-core/pull/68494.

**Comment by xavierleroy** [comment]
> Coq 8.13 now has a hard dependency on Zarith and can no longer use Num

I didn't know that!  Thanks for the info.

> , so Homebrew needs a formula for ocaml-zarith in analogy to ocaml-num.
> I did what I could to write that formula at Homebrew/homebrew-core#68494.

Thanks a lot for your efforts.  I have no experience with Homebrew packaging, so I can't help, but let's hope this will work.

**Comment by tchajed** [comment]
That worked out nicely, so both ocaml-zarith and Coq 8.13 are now in Homebrew.
