### ISSUE TITLE
asking for a release

### ISSUE THREAD

**Issue by hannesm** [ocaml/Zarith#96]
now that #79 and #94 are meged, it would be great to have a release of zarith :)

thanks a lot for your work.

**Comment by antoinemine** [comment]
I am waiting for results from some regression tests. I will make a release afterwards.

**Comment by hannesm** [comment]
Thanks for your work, and the release at https://github.com/ocaml/opam-repository/pull/18256 :)

**Comment by xavierleroy** [comment]
Thank you @antoinemine !
